name: quickassitnew
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.1.2
  svg_flutter: ^0.0.1
  intl: ^0.19.0
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.8.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.4
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  floating_bottom_navigation_bar: ^1.5.2
  animated_bottom_navigation_bar: ^1.3.3
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  image_picker: ^1.1.2
  uuid: ^4.5.1
  qr_flutter: ^4.1.0
  firebase_messaging: ^15.1.3
  onesignal_flutter: ^5.1.0
  pdf: ^3.10.4
  path_provider: ^2.1.5
  open_file: ^3.3.2
  printing: ^5.12.0
  razorpay_flutter: ^1.3.7
  firebase_app_check: ^0.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/json/
    - assets/svg/
