// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Updated with your real Firebase project configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIAkEkvW0eUR0K-uX3jxwmmaL5cFUM8ME',
    appId: '1:494241373838:web:5f363c1a47e880b5584780',
    messagingSenderId: '494241373838',
    projectId: 'quickassist-97d9a',
    authDomain: 'quickassist-97d9a.firebaseapp.com',
    storageBucket: 'quickassist-97d9a.firebasestorage.app',
  );

  // Updated with your real Firebase project configuration
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIAkEkvW0eUR0K-uX3jxwmmaL5cFUM8ME',
    appId: '1:494241373838:android:c5756ed2e4f6aea50d73df',
    messagingSenderId: '494241373838',
    projectId: 'quickassist-97d9a',
    storageBucket: 'quickassist-97d9a.firebasestorage.app',
  );

  // Updated with your real Firebase project configuration
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIAkEkvW0eUR0K-uX3jxwmmaL5cFUM8ME',
    appId: '1:494241373838:ios:7a1e572e9a7f454c584780',
    messagingSenderId: '494241373838',
    projectId: 'quickassist-97d9a',
    storageBucket: 'quickassist-97d9a.firebasestorage.app',
    iosBundleId: 'com.example.quickassistnew',
  );
}
